In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    "Name": ["A", "B"],
    "Score": [70, 85],
    "age":[21,14]
})

In [3]:
df2 = pd.DataFrame({
    "Name": ["C", "D"],
    "Score": [90, 60],
    "location":["chennai","tiruvallur"]
})

In [11]:
result = pd.concat([df1, df2])
print(result)

  Name  Score   age    location
0    A     70  21.0         NaN
1    B     85  14.0         NaN
0    C     90   NaN     chennai
1    D     60   NaN  tiruvallur

In [15]:
pd.concat([df1, df2], ignore_index=True
          )

  Name  Score   age    location
0    A     70  21.0         NaN
1    B     85  14.0         NaN
2    C     90   NaN     chennai
3    D     60   NaN  tiruvallur

In [20]:
pd.concat([df1, df2], axis=1
          )

  Name  Score  age Name  Score    location
0    A     70   21    C     90     chennai
1    B     85   14    D     60  tiruvallur

In [22]:
marks = [35, 48, 52, 67, 76, 89, 95]

In [23]:
bins = [0, 40, 60, 80, 100]
labels = ["Fail", "Pass", "Good", "Excellent"]

grades = pd.cut(marks, bins=bins, labels=labels)
print(grades)

['Fail', 'Pass', 'Pass', 'Good', 'Good', 'Excellent', 'Excellent']
Categories (4, object): ['Fail' < 'Pass' < 'Good' < 'Excellent']

In [26]:
sales = [100, 150, 200, 250, 300]
df = pd.DataFrame({"Sales": sales})
print(df)

   Sales
0    100
1    150
2    200
3    250
4    300

In [27]:
df["Running_Avg"] = df["Sales"].expanding().mean()
print(df)
df["Running_sum"] = df["Sales"].expanding().sum()
print(df)

   Sales  Running_Avg
0    100        100.0
1    150        125.0
2    200        150.0
3    250        175.0
4    300        200.0
   Sales  Running_Avg  Running_sum
0    100        100.0        100.0
1    150        125.0        250.0
2    200        150.0        450.0
3    250        175.0        700.0
4    300        200.0       1000.0

In [29]:
df1 = pd.DataFrame({"Sales": [100, 200]})
df2 = pd.DataFrame({"Sales": [300, 400]})

# Concat
df = pd.concat([df1, df2], ignore_index=True)

# Running Average
df["Running_Avg"] = df["Sales"].expanding().mean()

# Categorize sales
df["Category"] = pd.cut(
    df["Sales"],
    bins=[0, 200, 350, 500],
    labels=["Low", "Medium", "High"]
)

print(df)

   Sales  Running_Avg Category
0    100        100.0      Low
1    200        150.0      Low
2    300        200.0   Medium
3    400        250.0     High